package tiltadv.tools.scene;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

import static dhcoder.support.text.StringUtils.format;

/**
 * Panel which we show the user when the application first runs. It will contain useful tips to get someone started.
 */
public final class FirstRunPanel extends JPanel {
    private JLabel labelCommandWindow;

    public FirstRunPanel(final GlobalCommands globalCommands) {
        super();
        labelCommandWindow.setText(format("<html>Press <b>{0}</b> to open the command window</html>",
            globalCommands.showCommandWindow.getShortcutOpt().getValue()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        labelCommandWindow = new JLabel();
        labelCommandWindow.setText("(command window help text)");
        panel1.add(labelCommandWindow,
            new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }
}
