package tiltadv.tools.scene.forms;

import tiltadv.tools.scene.GlobalCommands;

import javax.swing.*;
import java.awt.*;

import static dhcoder.support.text.StringUtils.format;

/**
 * Panel which we show the user when the application first runs. It will contain useful tips to get someone started.
 */
public final class FirstRunForm {
    private JLabel labelCommandWindow;
    private JPanel panelRoot;

    public JPanel getPanelRoot() {
        return panelRoot;
    }

    public FirstRunForm(final GlobalCommands globalCommands) {
        super();
        labelCommandWindow.setText(format("<html>Press <b>{0}</b> to open the command window</html>",
            globalCommands.showCommandWindow.getShortcutOpt().getValue()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelRoot = new JPanel();
        panelRoot.setLayout(new BorderLayout(0, 0));
        labelCommandWindow = new JLabel();
        labelCommandWindow.setHorizontalAlignment(0);
        labelCommandWindow.setText("(command window help text)");
        panelRoot.add(labelCommandWindow, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return panelRoot; }
}
